### ISSUE TITLE
Related tables in ArcGIS Online???

### ISSUE THREAD

**Issue by BennyBaruba** [david-chambers/hackathon-handbook#25]
Explore options on how to use related tables in ArcGIS Online.  Is there a workflow that does not use ArcGIS desktop or Server

**Comment by david-chambers** [comment]
I think we could create a tool that does this using the REST API.  http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r30000009n000000 

I would like to take a stab at this one too.  I might test it out using the <a href=http://docs.python-requests.org/en/latest/>Requests</a> module of python and later make a web application that allows you to input two items, a common ID, and a relationship type (1:1, 1:M).  No Desktop required.

**Comment by david-chambers** [comment]
addRelationship endpoint isn't going to work :sob: This is establishing a relationship between the origin data and the service. Ex: the services that are in the web map.  The source data that was published to the service, etc.  I will keep looking for alternatives but think that desktop/arcpy may be the only way.

**Comment by BennyBaruba** [comment]
I figured this would be the case...thanks for exploring.

**Comment by david-chambers** [comment]
This isn't going to be possible without desktop software.
