### ISSUE TITLE
Update Information on hackathon-handbook page for MHACKS

### ISSUE THREAD

**Issue by BennyBaruba** [david-chambers/hackathon-handbook#42]
@jyaistMap 
Update the following on the hackathon-handbook page:
Change Voucher code to : MHAX
Update Open data links

**Comment by jyaistMap** [comment]
OK, dude. I did my homework…at least most of it.

I think there are 2 pull requests in the repo…but don’t accept them until After Saturday. Plus, I need to review with John G tomorrow to make sure I’m understanding the workflow.

I’m on my way!

John

**Comment by jgravois** [comment]
done via c254b98
