### ISSUE TITLE
suggestion: make gh-pages the default branch

### ISSUE THREAD

**Issue by jgravois** [david-chambers/hackathon-handbook#44]
and get rid of `master` entirely.

**Comment by david-chambers** [comment]
@jgravois This sounds like a great idea and would eliminate some redundant PRs! So long as gh-pages and master are up to date is this as easy as simply deleting master?

**Comment by jgravois** [comment]
> as easy as simply deleting master?

yup!
1. make sure `gh-pages` is in sync with `master`
2. set `gh-pages` as the default branch
3. delete `master`

an alternative, (although more work), is to skip creating pull requests to keep the two in sync, condemn committing directly in the `gh-pages` branch and allow contributors to fast forward by merging locally and push directly to `gh-pages` _after_ code review has happened on `master` (more info [here](https://github.com/Esri/developer-support/issues/61#issuecomment-120493093))

**Comment by david-chambers** [comment]
Sweet, all done and thanks for the tip! gh-pages is now our default branch and master has been deleted.
