### ISSUE TITLE
Add in slides for web APIs in slide deck

### ISSUE THREAD

**Issue by BennyBaruba** [david-chambers/hackathon-handbook#50]
Fill up the vertical slides for the Web API content (App Builder, JSAPI, Leaflet, etc...).  I recommend transfering the links from the old hackathon handbook page into a slide for each tech.  Using a vertical slide workflow.  Followed by a slide that just has one iframe showing one sample.  then at the stand up meeting we can decide which route we like the best.

On second thought maybe the following would be the best:
![img_20160210_155126750](https://cloud.githubusercontent.com/assets/5122225/12961418/603ac516-d00e-11e5-8ad8-1820b794a8c7.jpg)

Otherwise if we keep it all in one column...it would get to big.  That way John could just rip across the top slides for a high level overview or/and dive down from more info.  Hit me up if you have questions

**Comment by BennyBaruba** [comment]
![image](https://cloud.githubusercontent.com/assets/5122225/12962054/b17a48ae-d011-11e5-8825-dcdcce96cca6.png)
![image](https://cloud.githubusercontent.com/assets/5122225/12962064/baaf2cc8-d011-11e5-8103-1eb2e55eb445.png)
![image](https://cloud.githubusercontent.com/assets/5122225/12962070/c1444c1c-d011-11e5-9046-7342055767f5.png)

**Comment by david-chambers** [comment]
closed per #59
