### ISSUE TITLE
Add slides for mobile SDKs

### ISSUE THREAD

**Issue by BennyBaruba** [david-chambers/hackathon-handbook#51]
Add slide content in the following general layout.  Starting with App Studio, Android, iOS to begin with and then add info about the other runtime SDKs when we have time.
![img_20160210_160724608](https://cloud.githubusercontent.com/assets/5122225/12961869/a16674d4-d010-11e5-9ea2-13db15acb6ea.jpg)

Start with a main slide for a runtime SDK and then add vertical slides with samples and any other info.

**Comment by BennyBaruba** [comment]
![image](https://cloud.githubusercontent.com/assets/5122225/12962011/79070bd8-d011-11e5-921b-6fb04cb23d79.png)
![image](https://cloud.githubusercontent.com/assets/5122225/12962022/85085cfc-d011-11e5-9e5f-60b27ac47824.png)
![image](https://cloud.githubusercontent.com/assets/5122225/12962029/8cb0bdb4-d011-11e5-9e20-a6f9de8b4ab8.png)

**Comment by david-chambers** [comment]
@BennyBaruba Does #58 close this? We can always revisit formatting after demo tomorrow.

**Comment by david-chambers** [comment]
close per #58
