### ISSUE TITLE
The state of the hackathon-handbook.com domain

### ISSUE THREAD

**Issue by david-chambers** [david-chambers/hackathon-handbook#78]
Just wanted to drop a note that I renewed the hackathon-handbook.com domain that was set to expire on November 7th, 2016 for another year! It was only $2.88 so consider it my gift to the future of the book.  If anyone wants ownership of the domain feel free to let me know and I'll investigate how to transfer it. Heard you guys have a bunch of hacks coming up, hope you have fun!

@jyaistMap @BennyBaruba @stewrouse

**Comment by jyaistMap** [comment]
Thanks @david-chambers!!! Man are you generous ;)  If you can find out what we need to do to transfer ownership, I'll take it over from you.  Do we need to do anything with the github repo or are you cool with hanging out in it?  
Hope all is well with you and the new gig is working out. Brian mentioned things were good when I met him in Raleigh last month. Ben, Brian and I are working at HackNC this weekend - you can come hang out if you want :)
@BennyBaruba @stewrouse

**Comment by jyaistMap** [comment]
Hey David - Can you check with the domain to make sure they renewed it?  I tried to access it today and it will not pull up the handbook.

**Comment by david-chambers** [comment]
@jyaistMap good catch, looks like the renewal didn't get processed. It's alive and well now.
