### ISSUE TITLE
Migrate ownership of repository and domain registration

### ISSUE THREAD

**Issue by briantwatson** [david-chambers/hackathon-handbook#81]
To lessen the burden on @david-chambers, we've discussed transitioning the ownership of repository.  It would likely make most sense to either move to @jyaistMap or create a new Esri repository.

Logical order of operations:
1.  Move domain registration on namecheap to an account managed by @jyaistMap.
[Transferring domain](https://www.namecheap.com/support/knowledgebase/article.aspx/1187/8/how-can-i-move-a-domain-from-one-namecheap-account-to-another)
2.  Once we decide on resting location for the page, transfer ownership:
[Transfer repository ownership](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/)
3.  Update domain name records to point to new gh-pages

**Comment by briantwatson** [comment]
@david-chambers , we can probably stick a fork in this issue, and the domain name if you wish... from what @jyaistMap tells me, the program is over

**Comment by david-chambers** [comment]
Sounds good, the hackathon-handbook.com domain is in my possession until 11/6/2017.  I won't renew this year.
